### ISSUE TITLE
hello, how many GPU mem does it need to run stablefusioun and controlnet?

### ISSUE THREAD

**Issue by jinfagang** [DN6/giffusion#20]
hello, how many GPU mem does it need to run stablefusioun and controlnet?

**Comment by DN6** [comment]
Hello @jinfagang. I've tested using Controlnet's on Colab with  a T4 GPU (16GB VRAM). However, the Controlnet pipeline does use `pipe. enable_model_cpu_offload` which should let you use it with GPU's with lower memory.
